# Generated by Django 4.2.2 on 2023-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
